# Generated by Django 3.1 on 2021-02-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('tel1', models.IntegerField(blank=True, null=True)),
                ('tel2', models.IntegerField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=500)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('domicile_malade', models.CharField(blank=True, max_length=5000, null=True)),
                ('date_naissance', models.CharField(default=0, max_length=50)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(default=0, max_length=50)),
                ('Nom_urgence', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone_urgent', models.CharField(default=0, max_length=50)),
                ('Admission', models.CharField(max_length=50)),
                ('age', models.CharField(default=0, max_length=50)),
                ('resume', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('date_entree', models.CharField(default=0, max_length=50)),
                ('date_sortie', models.CharField(default=0, max_length=50)),
                ('diagnostique', models.TextField(blank=True, null=True)),
                ('examen', models.TextField(blank=True, null=True)),
                ('année', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnie', models.CharField(blank=True, max_length=100, null=True)),
                ('groupe_sang', models.CharField(blank=True, max_length=50, null=True)),
                ('rhesus', models.CharField(blank=True, max_length=100, null=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.hopital')),
                ('sexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.sexe')),
            ],
        ),
    ]
