# Generated by Django 3.1 on 2021-02-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='hopital',
        ),
        migrations.DeleteModel(
            name='Hopital',
        ),
    ]
