# Generated by Django 3.1 on 2021-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210226_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sexe',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
