# Generated by Django 3.1 on 2021-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210308_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hopital',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
