# Generated by Django 3.1 on 2021-03-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_contact_hopital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Admission',
            new_name='admission',
        ),
    ]
