# Generated by Django 3.1 on 2021-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210308_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='resultat_examen',
            field=models.FileField(default=1, upload_to='examen'),
            preserve_default=False,
        ),
    ]
